backend/routes/web.php
<?php

use App\Http\Controllers\AbonnemmentController;
use App\Http\Controllers\CategorieController;
use App\Http\Controllers\CitieController;
use App\Http\Controllers\EvenementController;
use App\Http\Controllers\FavorieController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home');
});
Route::get('/about', function () {
    return view('pages.about');
});
Route::get('/contact', function () {
    return view('pages.contact');
});

Route::get('/eventsLists',[EvenementController::class, 'ListEvents'])->name('eventsLists');
Route::get('/dashboard', function () {
    return view('dashboard.home');
})->name('dashboard');
Auth::routes();

Route::get('eventCreate',[EvenementController::class, 'index'])->name('eventCreate');
// Route::get('/login', [App\Http\Controllers\HomeController::class, 'index'])->name('login');

Route::resource('/favourites', FavorieController::class);
Route::resource('/categories', CategorieController::class);
Route::resource('/subscribes', AbonnemmentController::class);
Route::resource('/cities', CitieController::class);
Route::resource('/users', UserController::class);
Route::resource('/events', EvenementController::class);
//Categorie
Route::get('categorie/delete/{id}', [CategorieController::class, 'delete'])->name('delete');
Route::get('editCat/{id}', [CategorieController::class, 'editCat'])->name('editCat');
Route::put('updateCat', [CategorieController::class, 'updateCategorie'])->name('updateCat');
//Citie
Route::get('citie/delete/{id}', [CitieController::class, 'delete'])->name('deleteCitie');
Route::get('editCitie/{id}', [CitieController::class, 'editCitie'])->name('editCitie');
Route::put('updateCitie', [CitieController::class, 'updateCitie'])->name('updateCitie');

backend/resources/views/pages/event.blade.php
@extends('layouts.app')

@push('stylenav')
    <link href="{{ asset('css/navbar.css') }}" rel="stylesheet">
    {{-- <link href="{{ asset('css/eventCreate.css') }}" rel="stylesheet"> --}}
@endpush

@section('header')

    <header class="header_nav">
        <div>
            <a href="{{ url('/') }}" class="nav_env__name header_nav__logo">
                <span>Ach</span><span class="Nlogo__last">Kayn</span>
            </a>
        </div>
        <ion-icon name="menu-outline" class="header_nav__toggle" id="nav-toggle"></ion-icon>
        <nav class="nav_env" id="nav_env-menu">
            <div class="nav_env__content bd-grid">

                <ion-icon name="close-outline" class="nav_env__close" id="nav_env-close"></ion-icon>

                <div class="nav_env__perfil">
                    <div>
                        <a href="{{ url('/') }}" class="nav_env__name">
                            <span>Ach</span><span class="Nlogo__last">Kayn</span>
                        </a>
                    </div>
                </div>

                <div class="nav_env__menu">
                    <ul class="nav_env__list">
                        <li class="nav_env__item"><a href="{{ url('/') }}" class="nav_env__link">Home</a>
                        </li>
                        <li class="nav_env__item"><a href="{{ url('/about') }}" class="nav_env__link">About Us</a></li>
                        <li class="nav_env__item"><a href="{{ route('eventsLists') }}" class="nav_env__link">Events</a>
                        </li>
                        <li class="nav_env__item"><a href="{{ url('/contact') }}" class="nav_env__link">Contact Us</a>
                        </li>
                    </ul>
                </div>

                <div class="nav_env__social">

                    <a class="btn_event" href="{{ url('/eventCreate') }}"><i class="fas fa-pencil-alt"></i> Create
                        Event</a>
                    @auth
                    @else
                        <a class="btn_login" href="{{ url('/login') }}">Sign in</a>
                    @endauth
                    </a>
                </div>
            </div>
        </nav>
    </header>
@endsection
@section('content')

    <section class="section-container">

        <div class="create">
            <h1>{{ $eventInfo[0]->titre }}</h1>
            <br>
            <br>
            <div class="d-flex justify-content-center">
                <img src="{{ URL('assets/images/' . $eventInfo[0]->image) }}" style="width: 60em;"
                    alt="Image folder-rafiki" id="outputImage">
            </div>

            <hr>

            <p>
                {{ $eventInfo[0]->description }}
            </p>

            <hr>

            <div>
                <div>
                    {{ $eventInfo[0]->day }}
                </div>
                <div>
                    {{ $eventInfo[0]->time }}
                </div>
                <div>
                    {{ $eventInfo[0]->duree }}h
                </div>
            </div>
            <br>
            <hr>
            <br>

            <label for="city">City : {{ $eventInfo[0]->name }}</label>
            <label for="address">{{ $eventInfo[0]->addrese }}</label>
            <label for="user"> Created by : {{ $eventInfo[0]->firstName }} {{ $eventInfo[0]->lastName }}</label>
            <label for="address">created_at : {{ $eventInfo[0]->created_at }}</label>
            <div class="d-flex justify-content-center">
                <a class="btn_login" style="text-decoration: none;color: white;" href="#">Register To Event</a>
            </div>
        </div>

    </section>
    </form>
@endsection

@section('footer')
    @include('layouts.footer')
@endsection

backend/resources/views/pages/eventCreate.blade.php
@extends('layouts.app')

@push('stylenav')
    <link href="{{ asset('css/navbar.css') }}" rel="stylesheet">
    {{-- <link href="{{ asset('css/eventCreate.css') }}" rel="stylesheet"> --}}
@endpush

@section('header')

    <header class="header_nav">
        <div>
            <a href="{{ url('/') }}" class="nav_env__name header_nav__logo">
                <span>Ach</span><span class="Nlogo__last">Kayn</span>
            </a>
        </div>
        <ion-icon name="menu-outline" class="header_nav__toggle" id="nav-toggle"></ion-icon>
        <nav class="nav_env" id="nav_env-menu">
            <div class="nav_env__content bd-grid">

                <ion-icon name="close-outline" class="nav_env__close" id="nav_env-close"></ion-icon>

                <div class="nav_env__perfil">
                    <div>
                        <a href="{{ url('/') }}" class="nav_env__name">
                            <span>Ach</span><span class="Nlogo__last">Kayn</span>
                        </a>
                    </div>
                </div>

                <div class="nav_env__menu">
                    <ul class="nav_env__list">
                        <li class="nav_env__item"><a href="{{ url('/') }}" class="nav_env__link active_env">Home</a>
                        </li>
                        <li class="nav_env__item"><a href="{{ url('/about') }}" class="nav_env__link">About Us</a></li>
                        <li class="nav_env__item"><a href="{{ route('eventsLists') }}" class="nav_env__link">Events</a>
                        </li>
                        <li class="nav_env__item"><a href="{{ url('/contact') }}" class="nav_env__link">Contact Us</a>
                        </li>
                    </ul>
                </div>

                <div class="nav_env__social">

                    <a class="btn_event" href="{{ url('/eventCreate') }}"><i class="fas fa-pencil-alt"></i> Create
                        Event</a>
                    @auth
                    @else
                        <a class="btn_login" href="{{ url('/login') }}">Sign in</a>
                    @endauth
                    
                    </a>
                </div>
            </div>
        </nav>
    </header>
@endsection
@section('content')
    <form action="{{ route('events.store') }}" method="post" enctype="multipart/form-data">
        @csrf

        @if ($message = Session::get('success'))
            <div class="alert alert-success alert-block">
                <button type="button" class="close" data-dismiss="alert">×</button>
                <strong>{{ $message }}</strong>
            </div>
        @endif

        @if (count($errors) > 0)
            <div class="alert alert-danger">
                <strong>Whoops!</strong> There were some problems with your input.
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif
        <section class="section-container">

            <div class="create">
                <h1>Creat New Events</h1>
                <p>
                    Give your event a name.
                </p>
                <p>
                    See how your name appears on the event page and a list of all places
                    where your event name will be used
                </p>
                <input class="evant-input" name="titre" type="text" placeholder="entrer name event">
                <hr>
                <h3>Choose a category for your event.*</h3>
                <p>Choosing relevant categories helps to improve the discoverability of your event.</p>
                <div class="select-ev">
                    <select name="category">
                        <option value="">All Category</option>
                        @foreach ($categories as $cat)
                            <option value="{{ $cat->id }}">{{ $cat->name }}</option>
                        @endforeach
                    </select>
                </div>
                <hr>
                <h3>When is your event?</h3>
                <p>Tell your attendees when your event starts so they can get ready to attend.</p>
                <div class="adrsse-event">
                    <input type="date" name="day" placeholder="Enter the day of the event">
                    <input type="time" name="time" placeholder="Enter the event start time">
                    <input type="number" name="duration" placeholder="event duration">
                </div>
                <hr>
                <h3>Add a cover images to your event .</h3>
                <p>Upload cover images for your event!</p>
                <input type="file" accept=".png, .jpg, .jpeg .jpg , .png , .jpeg , .gif , .svg" class="btn btn-primary"
                    name="image" onchange="loadFile(event)">

                <br>
                <br>
                <br>
                <img src="{{ asset('images/Conference-amico.png') }}" style="width: 300px;" alt="Image folder-rafiki"
                    id="outputImage">
                <hr>

                {{-- @error('cover')
                    <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                @enderror --}}

                <h3>Please describe your event.</h3>
                <p>Write a few words below to describe your event and provide any extra information such as schedules,
                    itinerary
                    or any special instructions required to attend your event.</p>
                <textarea name="description" id="" cols="30" rows="10"
                    style="width: 1000px; height: 300px; margin:10px 20px"></textarea>
                <hr>
                <h3>
                    Where is your event taking place? *
                </h3>
                <p>
                    Add a venue to your event to tell your attendees where to join the event.
                </p>
                <div class="place-event">
                    <label for="city">City *</label>
                    <select name="city">
                        <option value="">All cities</option>
                        @foreach ($cities as $citie)
                            <option value="{{ $citie->id }}">{{ $citie->name }}</option>
                        @endforeach
                    </select>
                    <label for="address">Address *</label>
                    <input type="text" name="address" id="address">
                </div>
                <hr>
                <div class="valider-btn">
                    <input type="submit" class="valider-event" value="Valider">
                </div>

            </div>

        </section>
    </form>
    {{-- <form id="regForm" action="">

        <h1>Register:</h1>

        <!-- One "tab" for each step in the form: -->
        <div class="tab">Name:
            <p><input placeholder="First name..." oninput="this.className = ''"></p>
            <p><input placeholder="Last name..." oninput="this.className = ''"></p>
        </div>

        <div class="tab">Contact Info:
            <p><input placeholder="E-mail..." oninput="this.className = ''"></p>
            <p><input placeholder="Phone..." oninput="this.className = ''"></p>
        </div>

        <div class="tab">Birthday:
            <p><input placeholder="dd" oninput="this.className = ''"></p>
            <p><input placeholder="mm" oninput="this.className = ''"></p>
            <p><input placeholder="yyyy" oninput="this.className = ''"></p>
        </div>

        <div class="tab">Login Info:
            <p><input placeholder="Username..." oninput="this.className = ''"></p>
            <p><input placeholder="Password..." oninput="this.className = ''"></p>
        </div>

        <div style="overflow:auto;">
            <div style="float:right;">
                <button type="button" id="prevBtn" onclick="nextPrev(-1)">Previous</button>
                <button type="button" id="nextBtn" onclick="nextPrev(1)">Next</button>
            </div>
        </div>

        <!-- Circles which indicates the steps of the form: -->
        <div style="text-align:center;margin-top:40px;">
            <span class="step"></span>
            <span class="step"></span>
            <span class="step"></span>
            <span class="step"></span>
        </div>

    </form> --}}

@endsection
<script>
    let loadFile = function(event) {
        // alert('ok');
        let image = document.getElementById('outputImage');
        image.src = URL.createObjectURL(event.target.files[0]);
    }
</script>
@section('footer')
    @include('layouts.footer')
@endsection

backend/resources/views/pages/events.blade.php
@extends('layouts.app')

@push('stylenav')
    <link href="{{ asset('css/navbar.css') }}" rel="stylesheet">
@endpush

@section('header')

    <header class="header_nav">
        <div>
            <a href="{{ url('/') }}" class="nav_env__name header_nav__logo">
                <span>Ach</span><span class="Nlogo__last">Kayn</span>
            </a>
        </div>
        <ion-icon name="menu-outline" class="header_nav__toggle" id="nav-toggle"></ion-icon>
        <nav class="nav_env" id="nav_env-menu">
            <div class="nav_env__content bd-grid">

                <ion-icon name="close-outline" class="nav_env__close" id="nav_env-close"></ion-icon>

                <div class="nav_env__perfil">
                    <div>
                        <a href="{{ url('/') }}" class="nav_env__name">
                            <span>Ach</span><span class="Nlogo__last">Kayn</span>
                        </a>
                    </div>
                </div>

                <div class="nav_env__menu">
                    <ul class="nav_env__list">
                        <li class="nav_env__item"><a href="{{ url('/') }}" class="nav_env__link">Home</a>
                        </li>
                        <li class="nav_env__item"><a href="{{ url('/about') }}" class="nav_env__link">About Us</a></li>
                        <li class="nav_env__item active_en"><a href="{{ route('eventsLists') }}"
                                class="nav_env__link">Events</a></li>
                        <li class="nav_env__item"><a href="{{ url('/contact') }}" class="nav_env__link">Contact Us</a>
                        </li>
                    </ul>
                </div>

                <div class="nav_env__social">

                    <a class="btn_event" href="{{ url('/eventCreate') }}"><i class="fas fa-pencil-alt"></i> Create
                        Event</a>

                    @auth
                    @else
                        <a class="btn_login" href="{{ url('/login') }}">Sign in</a>
                    @endauth

                    {{-- <a class="btn_login" href="{{ url('/login') }}">Sign in</a> --}}
                    {{-- <div class="profile">
                        <i class="fas fa-user-circle"></i>
                        <p>Mohssine Elattari</p>
                        <i class="fas fa-caret-down"></i>
                    </div> --}}
                    </a>
                </div>
            </div>
        </nav>
    </header>
@endsection
@section('content')

    <section class="Event-Service">
        <div class="service-one">
            <div class="img-service">
                <img src="{{ asset('images/Learning-amico.png') }}" alt="Time management-amico">
            </div>
            <div class="info-service">
                <h3>
                    Know the events organized in Morocco according to the category
                    and the organizing institution.
                </h3>
                <p>
                    Look for an organized event ,
                    and Know all the information on each event
                    (description, time of organization, institution, place, etc.).
                </p>
                <p>
                    Know the statistics of attendees and events, and approval of requests to
                    attend the event.
                </p>
            </div>

        </div>
    </section>
    <section class="most-populer">
        <div class="container-most">
            <div class="filter-event">
                <div class="filter">
                    <a href="">Party</a>
                    <a href="">Wedding</a>
                    <a href="">Metting</a>
                </div>
                <div class="search">
                    <input type="text" placeholder="Filter by city">
                </div>
            </div>
            <div class="slider">
                @foreach ($events as $event)
                    <div class="card-event">
                        <div class="container-background">
                            <i class="far fa-heart"></i>
                            <img src="{{ url('assets/images/' . $event->image) }}" alt="">
                            <div class="time-event">
                                <p>{{ \Carbon\Carbon::parse($event->day)->format('d') }}<br>{{ \Carbon\Carbon::parse($event->day)->format('M') }}
                                </p>
                                {{-- <P>{{ \Carbon\Carbon::parse($event->day)->format('M') }}</P>
                                <P>{{ \Carbon\Carbon::parse($event->day)->format('m') }}</P> --}}

                                {{-- format('M') --}}
                                {{-- $comment->created_at)->diffForHumans() --}}
                            </div>
                        </div>
                        <div class="info-event">
                            <div class="title-event">
                                {{ $event->titre }}
                            </div>
                            <div class="adresss-ev">
                                {{ $event->addrese }}
                            </div>
                            <div class="info-time">
                                <div class="time">
                                    <i class="far fa-clock"></i>
                                    {{-- Sat 09:00 --}}
                                    {{ $event->time }}
                                </div>
                                <div class="Duration">
                                    <i class="fas fa-stopwatch"></i>
                                    {{-- 2h 30m --}}
                                    {{ $event->duree }}h

                                </div>
                                <div class="price">
                                    <i class="fas fa-dollar-sign"></i>
                                    Free
                                </div>
                            </div>
                            <div class="read-more">
                                <a href="{{ route('events.show', $event->id) }}">Read More</a>
                            </div>
                        </div>
                    </div>
                @endforeach
            </div>
        </div>
        <div class="d-flex justify-content-center">
            {!! $events->appends(['sort' => 'science-stream'])->links() !!}
        </div>
    </section>


@endsection
@section('footer')
    @include('layouts.footer')
@endsection