backend/routes/web.php
<?php

use App\Http\Controllers\AbonnemmentController;
use App\Http\Controllers\CategorieController;
use App\Http\Controllers\CitieController;
use App\Http\Controllers\EvenementController;
use App\Http\Controllers\FavorieController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home');
});
Route::get('/about', function () {
    return view('pages.about');
});
Route::get('/contact', function () {
    return view('pages.contact');
});

Route::get('/eventsLists',[EvenementController::class, 'ListEvents'])->name('eventsLists');
Route::get('/dashboard', function () {
    return view('dashboard.home');
})->name('dashboard');
Auth::routes();

Route::get('eventCreate',[EvenementController::class, 'index'])->name('eventCreate');
// Route::get('/login', [App\Http\Controllers\HomeController::class, 'index'])->name('login');

Route::resource('/favourites', FavorieController::class);
Route::resource('/categories', CategorieController::class);
Route::resource('/subscribes', AbonnemmentController::class);
Route::resource('/cities', CitieController::class);
Route::resource('/users', UserController::class);
Route::resource('/events', EvenementController::class);
//Categorie
Route::get('categorie/delete/{id}', [CategorieController::class, 'delete'])->name('delete');
Route::get('editCat/{id}', [CategorieController::class, 'editCat'])->name('editCat');
Route::put('updateCat', [CategorieController::class, 'updateCategorie'])->name('updateCat');
//Citie
Route::get('citie/delete/{id}', [CitieController::class, 'delete'])->name('deleteCitie');
Route::get('editCitie/{id}', [CitieController::class, 'editCitie'])->name('editCitie');
Route::put('updateCitie', [CitieController::class, 'updateCitie'])->name('updateCitie');

backend/resources/views/dashboard/categories.blade.php
@extends('layouts.dashboard')

@section('content')

    <div class="row my-5">
        <h2 class="fs-4 mb-1">Categories</h2>
        <div class="pull-right mb-3" style="display: flex;justify-content: flex-end;">
            <a class="btn btn-success " data-bs-toggle="modal" data-bs-target="#exampleModal" href=""> Create New
                Categorie</a>
        </div>

        <!-- Modal ADD-->
        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Add categorie</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <form action="{{ route('categories.store') }}" method="post" id="myForm2">
                        @csrf
                        <div class="modal-body">
                            <div class="mb-3">
                                <label for="name" class="form-label">Category Name :</label>
                                <input type="input" name="name" class="form-control">
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                            <button type="submit" class="btn btn-primary"
                                onclick="return confirm('are you sure you want to add this Catrgory')">Add</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        {{-- End Moal ADD --}}


        <!-- Modal UPDATE-->
        <div class="modal fade" id="updateModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Update categorie</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <form action="{{ route('updateCat') }}" method="post" id="myForm2">
                        @csrf
                        @method('PUT')
                        <input type="hidden" name="cat_id" id="cat_id">
                        <div class="modal-body">
                            <div class="mb-3">
                                <label for="name" class="form-label">Category Name :</label>
                                <input type="input" name="name" id="name" class="form-control">
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                            <button type="submit" class="btn btn-primary"
                                onclick="return confirm('are you sure you want to add this Catrgory')">Update</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        {{-- End Moal UPDATE --}}
        <div class="col">
            <table class="table bg-white rounded shadow-sm  table-hover table table-striped">
                <thead>
                    <tr>
                        <th scope="col" width="50">#</th>
                        <th scope="col">Name</th>
                        <th scope="col">Date created</th>
                        <th scope="col">Date update</th>
                        <th scope="col">Operation</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($categories as $cat)
                        <tr>

                            {{-- <form action="{{ route('categories.destroy', $cat->id) }}" method="POST" id="myForm"> --}}

                            <th scope="row">{{ $cat->id }}</th>
                            <td>{{ $cat->name }}</td>
                            <td>{{ $cat->created_at }}</td>
                            <td>{{ $cat->updated_at }}</td>
                            <td>
                                <button class="btn btn-success editbtn" value="{{ $cat->id }}">Edit</button>
                                {{-- @csrf --}}
                                <a class="btn btn-danger" href="categorie/delete/{{ $cat->id }}"
                                    onclick="return confirm('are you sure you want to delete this Catrgory')">Delete</a>
                                {{-- <form> --}}
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
            
            {{-- <span>{{ $categories->links() }}</span> --}}
            <div class="d-flex justify-content-center">
                {!! $categories->appends(['sort' => 'science-stream'])->links() !!}
            </div> 
        </div>

    </div>
    <script>
        // var myModal = document.getElementById('myModal')
        // var myInput = document.getElementById('myInput')

        // myModal.addEventListener('shown.bs.modal', function() {
        //     myInput.focus()
        // })


        $(document).ready(function() {
            $(document).on('click', '.editbtn', function() {
                let catId = $(this).val();
                $('#updateModal').modal('show');
                $.ajax({
                    type: "GET",
                    url: "/editCat/" + catId,
                    success: function(response) {
                        // console.log(response.categorie.name);
                        $('#cat_id').val(response.categorie.id)
                        $('#name').val(response.categorie.name)
                    }
                })
            });
        });

        function add() {
            console.log("awaw");
            document.getElementById("myForm2").submit();
        }

        $('.show_confirm').click(function(event) {
            var form = $(this).closest("form");
            var name = $(this).data("name");
            event.preventDefault();
            swal({
                    title: `Are you sure you want to delete this Category?`,
                    text: "If you delete this, it will be gone forever.",
                    icon: "warning",
                    buttons: true,
                    dangerMode: true,
                })
                .then((willDelete) => {
                    if (willDelete) {
                        document.getElementById("myForm").submit();
                    }
                });
        });
    </script>
@endsection

backend/resources/views/dashboard/cities.blade.php
@extends('layouts.dashboard')

@section('content')

    <div class="row my-5">
        <h2 class="fs-4 mb-1">Cities</h2>
        <div class="pull-right mb-3" style="display: flex;justify-content: flex-end;">
            <a class="btn btn-success " data-bs-toggle="modal" data-bs-target="#exampleModal" href=""> Create New
                Citie</a>
        </div>

        <!-- Modal ADD-->
        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Add citie</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <form action="{{ route('cities.store') }}" method="post" id="myForm2">
                        @csrf
                        <div class="modal-body">
                            <div class="mb-3">
                                <label for="name" class="form-label">Citie Name :</label>
                                <input type="input" name="name" class="form-control">
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                            <button type="submit" class="btn btn-primary"
                                onclick="return confirm('are you sure you want to add this Citie')">Add</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        {{-- End Moal ADD --}}


        <!-- Modal UPDATE-->
        <div class="modal fade" id="updateModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Update citie</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <form action="{{ route('updateCitie') }}" method="post" id="myForm2">
                        @csrf
                        @method('PUT')
                        <input type="hidden" name="citie_id" id="citie_id">
                        <div class="modal-body">
                            <div class="mb-3">
                                <label for="name" class="form-label">Category Name :</label>
                                <input type="input" name="name" id="name" class="form-control">
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                            <button type="submit" class="btn btn-primary"
                                onclick="return confirm('are you sure you want to add this Citie')">Update</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        {{-- End Moal UPDATE --}}
        <div class="col">
            <table class="table bg-white rounded shadow-sm  table-hover table table-striped">
                <thead>
                    <tr>
                        <th scope="col" width="50">#</th>
                        <th scope="col">Name</th>
                        <th scope="col">Date created</th>
                        <th scope="col">Date update</th>
                        <th scope="col">Operation</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($cities as $citie)
                        <tr>

                            {{-- <form action="{{ route('cities.destroy', $citie->id) }}" method="POST" id="myForm"> --}}

                            <th scope="row">{{ $citie->id }}</th>
                            <td>{{ $citie->name }}</td>
                            <td>{{ $citie->created_at }}</td>
                            <td>{{ $citie->updated_at }}</td>
                            <td>
                                <button class="btn btn-success editbtn" value="{{ $citie->id }}">Edit</button>
                                {{-- @csrf --}}
                                <a class="btn btn-danger" href="citie/delete/{{ $citie->id }}"
                                    onclick="return confirm('are you sure you want to delete this Citie')">Delete</a>
                                {{-- <form> --}}
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
            
            {{-- <span>{{ $cities->links() }}</span> --}}
            <div class="d-flex justify-content-center">
                {{-- {{ $cities->links() }} --}}
                {{-- {{ $collection->links() }} --}}
                {!! $cities->appends(['sort' => 'science-stream'])->links() !!}
            </div> 
        </div>

    </div>
    <script>
        // var myModal = document.getElementById('myModal')
        // var myInput = document.getElementById('myInput')

        // myModal.addEventListener('shown.bs.modal', function() {
        //     myInput.focus()
        // })


        $(document).ready(function() {
            $(document).on('click', '.editbtn', function() {
                let citie_id = $(this).val();
                $('#updateModal').modal('show');
                $.ajax({
                    type: "GET",
                    url: "/editCitie/" + citie_id,
                    success: function(response) {
                        // console.log(response.citie.name);
                        $('#citie_id').val(response.citie.id)
                        $('#name').val(response.citie.name)
                    }
                })
            });
        });

        function add() {
            // console.log("awaw");
            document.getElementById("myForm2").submit();
        }

        $('.show_confirm').click(function(event) {
            var form = $(this).closest("form");
            var name = $(this).data("name");
            event.preventDefault();
            swal({
                    title: `Are you sure you want to delete this Category?`,
                    text: "If you delete this, it will be gone forever.",
                    icon: "warning",
                    buttons: true,
                    dangerMode: true,
                })
                .then((willDelete) => {
                    if (willDelete) {
                        document.getElementById("myForm").submit();
                    }
                });
        });
    </script>
@endsection

backend/resources/views/dashboard/events.blade.php
@extends('layouts.admin')

@section('content')

<div class="row my-5">
    <h3 class="fs-4 mb-3">Recent Orders</h3>
    <div class="col">
        <table class="table bg-white rounded shadow-sm  table-hover">
            <thead>
                <tr>
                    <th scope="col" width="50">#</th>
                    <th scope="col">Product</th>
                    <th scope="col">Customer</th>
                    <th scope="col">Price</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <th scope="row">1</th>
                    <td>Television</td>
                    <td>Jonny</td>
                    <td>$1200</td>
                </tr>
                <tr>
                    <th scope="row">2</th>
                    <td>Laptop</td>
                    <td>Kenny</td>
                    <td>$750</td>
                </tr>
                <tr>
                    <th scope="row">3</th>
                    <td>Cell Phone</td>
                    <td>Jenny</td>
                    <td>$600</td>
                </tr>
                <tr>
                    <th scope="row">4</th>
                    <td>Fridge</td>
                    <td>Killy</td>
                    <td>$300</td>
                </tr>
                <tr>
                    <th scope="row">5</th>
                    <td>Books</td>
                    <td>Filly</td>
                    <td>$120</td>
                </tr>
                <tr>
                    <th scope="row">6</th>
                    <td>Gold</td>
                    <td>Bumbo</td>
                    <td>$1800</td>
                </tr>
                <tr>
                    <th scope="row">7</th>
                    <td>Pen</td>
                    <td>Bilbo</td>
                    <td>$75</td>
                </tr>
                <tr>
                    <th scope="row">8</th>
                    <td>Notebook</td>
                    <td>Frodo</td>
                    <td>$36</td>
                </tr>
                <tr>
                    <th scope="row">9</th>
                    <td>Dress</td>
                    <td>Kimo</td>
                    <td>$255</td>
                </tr>
                <tr>
                    <th scope="row">10</th>
                    <td>Paint</td>
                    <td>Zico</td>
                    <td>$434</td>
                </tr>
                <tr>
                    <th scope="row">11</th>
                    <td>Carpet</td>
                    <td>Jeco</td>
                    <td>$1236</td>
                </tr>
                <tr>
                    <th scope="row">12</th>
                    <td>Food</td>
                    <td>Haso</td>
                    <td>$422</td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
@endsection

backend/resources/views/dashboard/favourites.blade.php
@extends('layouts.dashboard')

@section('content')

<div class="row my-5">
    <h3 class="fs-4 mb-3">Recent Orders</h3>
    <div class="col">
        <table class="table bg-white rounded shadow-sm  table-hover">
            <thead>
                <tr>
                    <th scope="col" width="50">#</th>
                    <th scope="col">Product</th>
                    <th scope="col">Customer</th>
                    <th scope="col">Price</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <th scope="row">1</th>
                    <td>Television</td>
                    <td>Jonny</td>
                    <td>$1200</td>
                </tr>
                <tr>
                    <th scope="row">2</th>
                    <td>Laptop</td>
                    <td>Kenny</td>
                    <td>$750</td>
                </tr>
                <tr>
                    <th scope="row">3</th>
                    <td>Cell Phone</td>
                    <td>Jenny</td>
                    <td>$600</td>
                </tr>
                <tr>
                    <th scope="row">4</th>
                    <td>Fridge</td>
                    <td>Killy</td>
                    <td>$300</td>
                </tr>
                <tr>
                    <th scope="row">5</th>
                    <td>Books</td>
                    <td>Filly</td>
                    <td>$120</td>
                </tr>
                <tr>
                    <th scope="row">6</th>
                    <td>Gold</td>
                    <td>Bumbo</td>
                    <td>$1800</td>
                </tr>
                <tr>
                    <th scope="row">7</th>
                    <td>Pen</td>
                    <td>Bilbo</td>
                    <td>$75</td>
                </tr>
                <tr>
                    <th scope="row">8</th>
                    <td>Notebook</td>
                    <td>Frodo</td>
                    <td>$36</td>
                </tr>
                <tr>
                    <th scope="row">9</th>
                    <td>Dress</td>
                    <td>Kimo</td>
                    <td>$255</td>
                </tr>
                <tr>
                    <th scope="row">10</th>
                    <td>Paint</td>
                    <td>Zico</td>
                    <td>$434</td>
                </tr>
                <tr>
                    <th scope="row">11</th>
                    <td>Carpet</td>
                    <td>Jeco</td>
                    <td>$1236</td>
                </tr>
                <tr>
                    <th scope="row">12</th>
                    <td>Food</td>
                    <td>Haso</td>
                    <td>$422</td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
@endsection

backend/resources/views/dashboard/home.blade.php
@extends('layouts.dashboard')

@section('content')

<div class="row my-5">
    <h3 class="fs-4 mb-3">Recent Orders</h3>
    <div class="col">
        <table class="table bg-white rounded shadow-sm  table-hover">
            <thead>
                <tr>
                    <th scope="col" width="50">#</th>
                    <th scope="col">Product</th>
                    <th scope="col">Customer</th>
                    <th scope="col">Price</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <th scope="row">1</th>
                    <td>Television</td>
                    <td>Jonny</td>
                    <td>$1200</td>
                </tr>
                <tr>
                    <th scope="row">2</th>
                    <td>Laptop</td>
                    <td>Kenny</td>
                    <td>$750</td>
                </tr>
                <tr>
                    <th scope="row">3</th>
                    <td>Cell Phone</td>
                    <td>Jenny</td>
                    <td>$600</td>
                </tr>
                <tr>
                    <th scope="row">4</th>
                    <td>Fridge</td>
                    <td>Killy</td>
                    <td>$300</td>
                </tr>
                <tr>
                    <th scope="row">5</th>
                    <td>Books</td>
                    <td>Filly</td>
                    <td>$120</td>
                </tr>
                <tr>
                    <th scope="row">6</th>
                    <td>Gold</td>
                    <td>Bumbo</td>
                    <td>$1800</td>
                </tr>
                <tr>
                    <th scope="row">7</th>
                    <td>Pen</td>
                    <td>Bilbo</td>
                    <td>$75</td>
                </tr>
                <tr>
                    <th scope="row">8</th>
                    <td>Notebook</td>
                    <td>Frodo</td>
                    <td>$36</td>
                </tr>
                <tr>
                    <th scope="row">9</th>
                    <td>Dress</td>
                    <td>Kimo</td>
                    <td>$255</td>
                </tr>
                <tr>
                    <th scope="row">10</th>
                    <td>Paint</td>
                    <td>Zico</td>
                    <td>$434</td>
                </tr>
                <tr>
                    <th scope="row">11</th>
                    <td>Carpet</td>
                    <td>Jeco</td>
                    <td>$1236</td>
                </tr>
                <tr>
                    <th scope="row">12</th>
                    <td>Food</td>
                    <td>Haso</td>
                    <td>$422</td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
@endsection

backend/resources/views/dashboard/subscribes.blade.php
@extends('layouts.dashboard')

@section('content')

<div class="row my-5">
    <h3 class="fs-4 mb-3">Recent Orders</h3>
    <div class="col">
        <table class="table bg-white rounded shadow-sm  table-hover">
            <thead>
                <tr>
                    <th scope="col" width="50">#</th>
                    <th scope="col">Product</th>
                    <th scope="col">Customer</th>
                    <th scope="col">Price</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <th scope="row">1</th>
                    <td>Television</td>
                    <td>Jonny</td>
                    <td>$1200</td>
                </tr>
                <tr>
                    <th scope="row">2</th>
                    <td>Laptop</td>
                    <td>Kenny</td>
                    <td>$750</td>
                </tr>
                <tr>
                    <th scope="row">3</th>
                    <td>Cell Phone</td>
                    <td>Jenny</td>
                    <td>$600</td>
                </tr>
                <tr>
                    <th scope="row">4</th>
                    <td>Fridge</td>
                    <td>Killy</td>
                    <td>$300</td>
                </tr>
                <tr>
                    <th scope="row">5</th>
                    <td>Books</td>
                    <td>Filly</td>
                    <td>$120</td>
                </tr>
                <tr>
                    <th scope="row">6</th>
                    <td>Gold</td>
                    <td>Bumbo</td>
                    <td>$1800</td>
                </tr>
                <tr>
                    <th scope="row">7</th>
                    <td>Pen</td>
                    <td>Bilbo</td>
                    <td>$75</td>
                </tr>
                <tr>
                    <th scope="row">8</th>
                    <td>Notebook</td>
                    <td>Frodo</td>
                    <td>$36</td>
                </tr>
                <tr>
                    <th scope="row">9</th>
                    <td>Dress</td>
                    <td>Kimo</td>
                    <td>$255</td>
                </tr>
                <tr>
                    <th scope="row">10</th>
                    <td>Paint</td>
                    <td>Zico</td>
                    <td>$434</td>
                </tr>
                <tr>
                    <th scope="row">11</th>
                    <td>Carpet</td>
                    <td>Jeco</td>
                    <td>$1236</td>
                </tr>
                <tr>
                    <th scope="row">12</th>
                    <td>Food</td>
                    <td>Haso</td>
                    <td>$422</td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
@endsection

backend/resources/views/dashboard/users.blade.php
@extends('layouts.dashboard')

@section('content')

<div class="row my-5">
    <h3 class="fs-4 mb-3">Recent Orders</h3>
    <div class="col">
        <table class="table bg-white rounded shadow-sm  table-hover">
            <thead>
                <tr>
                    <th scope="col" width="50">#</th>
                    <th scope="col">Product</th>
                    <th scope="col">Customer</th>
                    <th scope="col">Price</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <th scope="row">1</th>
                    <td>Television</td>
                    <td>Jonny</td>
                    <td>$1200</td>
                </tr>
                <tr>
                    <th scope="row">2</th>
                    <td>Laptop</td>
                    <td>Kenny</td>
                    <td>$750</td>
                </tr>
                <tr>
                    <th scope="row">3</th>
                    <td>Cell Phone</td>
                    <td>Jenny</td>
                    <td>$600</td>
                </tr>
                <tr>
                    <th scope="row">4</th>
                    <td>Fridge</td>
                    <td>Killy</td>
                    <td>$300</td>
                </tr>
                <tr>
                    <th scope="row">5</th>
                    <td>Books</td>
                    <td>Filly</td>
                    <td>$120</td>
                </tr>
                <tr>
                    <th scope="row">6</th>
                    <td>Gold</td>
                    <td>Bumbo</td>
                    <td>$1800</td>
                </tr>
                <tr>
                    <th scope="row">7</th>
                    <td>Pen</td>
                    <td>Bilbo</td>
                    <td>$75</td>
                </tr>
                <tr>
                    <th scope="row">8</th>
                    <td>Notebook</td>
                    <td>Frodo</td>
                    <td>$36</td>
                </tr>
                <tr>
                    <th scope="row">9</th>
                    <td>Dress</td>
                    <td>Kimo</td>
                    <td>$255</td>
                </tr>
                <tr>
                    <th scope="row">10</th>
                    <td>Paint</td>
                    <td>Zico</td>
                    <td>$434</td>
                </tr>
                <tr>
                    <th scope="row">11</th>
                    <td>Carpet</td>
                    <td>Jeco</td>
                    <td>$1236</td>
                </tr>
                <tr>
                    <th scope="row">12</th>
                    <td>Food</td>
                    <td>Haso</td>
                    <td>$422</td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
@endsection